services:
  postgresql:
    container_name: elixir-postgres-tcp
    image: postgres:17-bookworm
    ports:
      - "127.0.0.1:5555:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=elixirdb
    volumes:
      - elixir-volume-postgres:/var/lib/postgresql/data
volumes:
  elixir-volume-postgres:
