version: '3'

services:
  postgresql:
    container_name: backend-toy-postgres
    image: postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
